#
###################################
# Site wide configuration
####################################
#
title: Your awesome title
email: e.wen.e.wen@163.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description..
url: https://993318936.github.io/blog # the base hostname & protocol for your site
keywords: ["jekyll", "java", "scala","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Nanjing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
   - jekyll-gist
   - jemoji
   - jekyll-feed

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Linhui, Li
  avatar: avatar.jpg
  job: "前端工程师"
  bio: "富有热情和好奇心"
  email: e.wen.e.wen@163.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: 993318936 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
